### ISSUE TITLE
How to deploy on windows node.js

### ISSUE THREAD

**Issue by 0x0sid** [PebbleRoad/web-calculator-app#1]
Hi guys, sorry to ask you that, but can you please tell me the process to install it. 
After I did bower install, I tried to lunch app.js with node but I get this error: 

`C:\Users\sbe\Desktop\web-calculator-app-master\scripts\app>node app.js
C:\Users\sbe\Desktop\web-calculator-app-master\scripts\app\app.js:930
})(jQuery, Handlebars)
   ^

ReferenceError: jQuery is not defined
    at Object.<anonymous> (C:\Users\sbe\Desktop\web-calculator-app-master\script
s\app\app.js:930:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

C:\Users\sbe\Desktop\web-calculator-app-master\scripts\app>`

**Comment by rmdort** [comment]
This library will only run on browser environment. Open `index.html` in a browser to view the calculator.
